# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
brews:
  - name: grump
    tap:
      owner: dhulihan
      name: homebrew-grump
    download_strategy: CurlDownloadStrategy
    folder: formula
    homepage: "https://github.com/dhulihan/grump"
builds:
- env:
  - CGO_ENABLED=1
  goos:
    - darwin
  goarch:
    - amd64
  ignore:
    - goos: freebsd
    - goos: linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
