version: '3'
services:
  build-linux:
    image: gobuilder
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /data
    volumes:
      - ".:/data"
    entrypoint:
      - ./scripts/build-linux.sh
